### ISSUE TITLE
Classes completely missing.

### ISSUE THREAD

**Issue by ArminKleinert** [LevitatingBusinessMan/rulox#2]
Classes are not supported. Is that what you meant by "I tried to avoid real OOP"?

**Comment by LevitatingBusinessMan** [comment]
Hey Armin, thanks for taking interest in the project.

I never added classes. This is stated in the first line of the README.
Instead I immediately moved onto the second part of the book, the bytecode vm.
What I meant with "I tried to avoid real OOP" is that I didn't want to use classes where I didn't have to (instead I used a lot of classes to mimic the behavior of Ruby modules, because I wrote this before I knew of modules). The book has this part written in Java so the example code is really object oriented.

Feel free to fork this and try to implement classes on your own.
